### ISSUE TITLE
show images in my-sites dashlet

### ISSUE THREAD

**Issue by folivares** [dgcloud/alfresco-share-site-logo-customization#6]
Hi! I can't show site logo in my-sites dashlet. Is it possible to retrieve the site logo node in share dashlet? Thanks

**Comment by douglascrp** [comment]
That's something the addon doesn't do.
You will have it customize the dashlet to do that

Em qua, 4 de nov de 2015 13:37, federix notifications@github.com escreveu:

> Hi! I can't show site logo in my-sites dashlet. Is it possible to retrieve
> the site logo node in share dashlet? Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/douglascrp/alfresco-share-site-logo-customization/issues/6
> .
> 
> ## 

Douglas C. R. Paes

**Comment by folivares** [comment]
I don't know how can access the site_logo node in dashlet because I can't search nodes with simple user account. Have you any idea?

**Comment by folivares** [comment]
I found how I can show site_logo in dashlet

```
var siteId = page.url.templateArgs.site;
var p = sitedata.getPage("site/" + siteId + "/dashboard");
var siteLogo = p.properties.siteLogo;
```

The problem is only on my-sites dashlet because it uses widget.

**Comment by douglascrp** [comment]
Right. You will have to customize it to include that

Em qua, 4 de nov de 2015 15:05, federix notifications@github.com escreveu:

> I found how I can show site_logo in dashlet
> 
> var siteId = page.url.templateArgs.site;
> var p = sitedata.getPage("site/" + siteId + "/dashboard");
> var siteLogo = p.properties.siteLogo;
> 
> The problem is only on my-sites dashlet because it uses widget.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/douglascrp/alfresco-share-site-logo-customization/issues/6#issuecomment-153793433
> .
> 
> ## 

Douglas C. R. Paes

**Comment by douglascrp** [comment]
@folivares Hello

With the new version I've just released, the dashlet now shows the custom logo.
