### ISSUE TITLE
building from source

### ISSUE THREAD

**Issue by digcat** [dgcloud/alfresco-share-site-logo-customization#7]
when building the sdk version is no longer available. bumping to 2.1.1 allows a successful build but your get errors 

 2016-01-28 17:45:32,794  ERROR [surf.extensibility.XMLHelper] [ajp-apr-8009-exec-6] The required element <sourcePackageRoot> was not found in element <customization>
 2016-01-28 17:45:55,166  ERROR [surf.extensibility.XMLHelper] [ajp-apr-8009-exec-2] The required element <sourcePackageRoot> was not found in element <customization>

and the upload graphic feature, keeps returning a 404 error.

**Comment by douglascrp** [comment]
@digcat which Alfresco version?

**Comment by digcat** [comment]
hi Douglas its been a while, suspect it would be 5.0.d, think I was trying to build a fresh amp, hence why had the issue with the sdk, will give 5.1 a test, but will you also keep 5.0.d version?

**Comment by douglascrp** [comment]
@digcat well, it works with 5.0.d, but if I'm not wrong, you told me at the time that you were trying it agains 5.1.

**Comment by digcat** [comment]
yes, actually your right, sorry!  that's why I tried bumping the sdk.  Interestingly are you moving to 2.2 sdk? will that prevent working on 5.0.d

**Comment by douglascrp** [comment]
I'm testing it right now

Em qui, 17 de mar de 2016 10:45, Digital Catalyst notifications@github.com
escreveu:

> yes, actually your right, sorry! that's why I tried bumping the sdk.
> Interestingly are you moving to 2.2 sdk? will that prevent working on 5.0.d
> 
> —
> You are receiving this because you commented.
> 
> Reply to this email directly or view it on GitHub
> https://github.com/douglascrp/alfresco-share-site-logo-customization/issues/7#issuecomment-197874890
> 
> ## 

Douglas C. R. Paes

**Comment by douglascrp** [comment]
@digcat I've just finished my tests against 5.1.e and it's working without any changes.
Can you check if that was the issue?
I'm asking you this because you say that you can't build from sources and that you get a 404 error when trying to use.

**Comment by douglascrp** [comment]
@digcat I'm closing this.
You can reopen it if you think it needs more information/investigation.
